import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { GoogleGenAI } from '@google/genai';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = parseInt(process.env.PORT || '3000', 10);

app.use(cors());
app.use(express.json({ limit: '60mb' }));
app.use(express.urlencoded({ extended: true, limit: '60mb' }));

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

app.post('/api/transcribe', async (req, res) => {
  try {
    const { audioData, mimeType = 'audio/x-m4a', model = 'gemini-3.5-flash', prompt } = req.body;

    if (!audioData) {
      return res.status(400).json({ error: 'Audio data is required.' });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.status(500).json({
        error: 'Gemini API key is not configured on the server. Please verify your environment settings.',
      });
    }

    const transcriptionPrompt = prompt || 
      'Please transcribe this audio faithfully and accurately as spoken. Output only the clear, verbatim transcription text without conversational filler, intros, or summaries.';

    const response = await ai.models.generateContent({
      model: model,
      contents: [
        {
          role: 'user',
          parts: [
            {
              inlineData: {
                mimeType: mimeType || 'audio/x-m4a',
                data: audioData,
              },
            },
            {
              text: transcriptionPrompt,
            },
          ],
        },
      ],
    });

    const text = response.text;
    if (!text) {
      return res.status(500).json({ error: 'No transcription text was generated by the model.' });
    }

    return res.json({ text });
  } catch (error: any) {
    console.error('Server transcription error:', error);
    let message = error?.message || 'Transcription failed.';

    if (typeof message === 'string') {
      if (message.includes('Quota exceeded') || message.includes('RESOURCE_EXHAUSTED')) {
        message = `Quota exceeded for model '${req.body?.model}'. This model may require a paid AI Studio plan or has reached quota limits. Please switch to Gemini 3.5 Flash or Gemini 2.5 Flash for immediate free-tier transcription.`;
      } else if (message.includes('PERMISSION_DENIED') || message.includes('caller does not have permission')) {
        message = `Access permission error for model '${req.body?.model}'. Please ensure your API key has appropriate permissions or choose Gemini 3.5 Flash / Gemini 2.5 Flash.`;
      }
    }

    return res.status(500).json({ error: message });
  }
});

app.get('/api/health', (_req, res) => {
  res.json({
    status: 'ok',
    serverKeyAvailable: !!process.env.GEMINI_API_KEY,
  });
});

async function startServer() {
  if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  } else {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true, host: '0.0.0.0' },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer().catch(console.error);
