export async function transcribeAudio(
  base64Data: string, 
  mimeType: string = 'audio/x-m4a', 
  model: string = "gemini-3.5-flash"
): Promise<string> {
  const response = await fetch('/api/transcribe', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      audioData: base64Data,
      mimeType: mimeType || 'audio/x-m4a',
      model: model,
    }),
  });

  const data = await response.json().catch(() => null);

  if (!response.ok) {
    const errorMsg = data?.error || `Server responded with status ${response.status} (${response.statusText})`;
    throw new Error(errorMsg);
  }

  if (!data?.text) {
    throw new Error("No transcription was generated by the service.");
  }

  return data.text;
}
